version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    groups:
      prod-deps:
        patterns:
          - "*"
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      gha-patches-minors:
        patterns:
          - "*"
