version: '3.8'
services:
  soap-api:
    container_name: soap-rest-gateway-dev
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./logs:/app/logs
    command: npx nodemon src/server.ts
    restart: unless-stopped
