version: '3.8'
networks:
  app-net:
    driver: bridge
services:
  soap-api:
    container_name: soap-rest-gateway
    build: .
    ports:
      - "3000:3000"
    networks: 
      - app-net
    environment:
      - PORT=${PORT}
    env_file:
      - .env
    volumes:
      - ./:/dist
      - ./logs:/dist/logs
    restart: unless-stopped
